-- Use the database OnlineSales
USE OnlineSales

-- Set key columns as NOT NULL and add primary key constraints

-- For orders_fact table
ALTER TABLE orders_fact
ALTER COLUMN OrdersKey INT NOT NULL;

ALTER TABLE orders_fact
ALTER COLUMN CustomerKey INT NOT NULL;

ALTER TABLE orders_fact
ALTER COLUMN ProductKey INT NOT NULL;

ALTER TABLE orders_fact
ALTER COLUMN DateKey INT NOT NULL;

ALTER TABLE orders_fact
ADD CONSTRAINT PK_orders_fact PRIMARY KEY(OrdersKey);

-- For customer_dim table
ALTER TABLE customer_dim
ALTER COLUMN CustomerKey INT NOT NULL;

ALTER TABLE customer_dim
ADD CONSTRAINT PK_customer_dim PRIMARY KEY(CustomerKey);

-- For product_dim table
ALTER TABLE product_dim
ALTER COLUMN ProductKey INT NOT NULL;

ALTER TABLE product_dim
ADD CONSTRAINT PK_product_dim PRIMARY KEY(ProductKey);

-- For date_dim table
ALTER TABLE date_dim
ALTER COLUMN DateKey INT NOT NULL;

ALTER TABLE date_dim
ADD CONSTRAINT PK_date_dim PRIMARY KEY(DateKey);

-- Set foreign key constraints
ALTER TABLE orders_fact
ADD CONSTRAINT FK_orders_customer FOREIGN KEY(CustomerKey) REFERENCES customer_dim(CustomerKey);

ALTER TABLE orders_fact
ADD CONSTRAINT FK_orders_product FOREIGN KEY(ProductKey) REFERENCES product_dim(ProductKey);

ALTER TABLE orders_fact
ADD CONSTRAINT FK_orders_date FOREIGN KEY(DateKey) REFERENCES date_dim(DateKey);


-- 1. Which Five months generated the largest revenue?
SELECT TOP 5
    d.Month, 
    SUM(o.Amount) AS TotalRevenue
FROM 
    date_dim AS d
JOIN 
    orders_fact AS o ON d.DateKey = o.DateKey
GROUP BY 
    d.Month
ORDER BY TotalRevenue DESC;

-- 2. Which quarter had the biggest sales?
SELECT TOP 1
    d.Quarter, 
    SUM(o.Quantity) AS TotalSales
FROM 
    date_dim AS d
JOIN 
    orders_fact AS o ON d.DateKey = o.DateKey
GROUP BY
    d.Quarter
ORDER BY
    TotalSales DESC;

-- 3. Which five states and cities generated the most profit?
SELECT TOP 5
    c.State, c.City, SUM(profit) AS TotalProfit
FROM 
    customer_dim AS c
JOIN 
    orders_fact AS o ON c.CustomerKey = o.CustomerKey
GROUP BY 
    c.State, c.City 
ORDER BY TotalProfit DESC;

-- 4. What is the total quantity sold on weekends vs. weekdays?
SELECT 
    d.IsWeekend, 
    SUM(o.Quantity) AS TotalQuantitySold
FROM 
    date_dim AS d
JOIN 
    orders_fact AS o ON d.DateKey = o.DateKey
GROUP BY 
    d.IsWeekend;

-- 5. What are the total revenue and average revenue generated by returning vs. new customers?
WITH CTE_CustomerOrderCounts AS (
SELECT 
    c.CustomerKey,
    c.CustomerName,
    COUNT(DISTINCT o.OrderID) AS OrderCount,
    SUM(o.Amount) AS TotalRevenue
FROM 
    customer_dim c
JOIN 
    orders_fact o ON c.CustomerKey = o.CustomerKey
GROUP BY 
    c.CustomerKey, c.CustomerName
)
SELECT
    CASE 
        WHEN OrderCount > 1 THEN 'Returning'
        ELSE 'New'
    END AS CustomerType,
    COUNT(CustomerKey) AS CustomerCount,
    SUM(TotalRevenue) AS TotalRevenue,
    AVG(TotalRevenue) AS AvgRevenue
FROM CTE_CustomerOrderCounts
GROUP BY 
	CASE 
		WHEN OrderCount > 1 THEN 'Returning' 
		ELSE 'New'
    END;

-- 6. What are the three most popular payment modes in cities?
SELECT TOP 3
    o.PaymentMode, COUNT(c.City) AS NumberOfCity
FROM orders_fact AS o
    JOIN customer_dim AS c ON o.CustomerKey = c.CustomerKey
GROUP BY PaymentMode
ORDER BY NumberOfCity DESC;

-- 7. What is the top revenue-generating categories and sub-categories of products for each month?
WITH CTE_RankedRevenue AS (
    SELECT
        d.Month,
        p.Category,
        p.SubCategory,
        SUM(o.Amount) AS TotalRevenue,
        ROW_NUMBER() OVER (PARTITION BY d.Month ORDER BY SUM(o.Amount) DESC) AS RowNumber
    FROM orders_fact AS o
    JOIN product_dim AS p ON o.ProductKey = p.ProductKey
    JOIN date_dim AS d ON o.DateKey = d.DateKey
    GROUP BY d.Month, p.Category, p.SubCategory
)
SELECT Month, Category, SubCategory, TotalRevenue
FROM CTE_RankedRevenue
WHERE RowNumber = 1;