/*
=================================================================================
Exploratory Data Analysis (EDA) in SQL Server
---------------------------------------------------------------------------------
Script Purpose:
	This script explores the database and the tables in the database by:
    - identifying tables and columns in the database
    - identifying unique values/categories in each dimension
    - calculating key metrics and building a report for the calculations
    - comparing the measure values by different categories
    - identifying the Top N performers and Bottom N performers
=================================================================================
*/


---------------------------------------------------------------------------------
-- Database Exploration: identifying tables and columns in the database
---------------------------------------------------------------------------------

-- Exlplore tables in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Exlplore columns in each table

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_products'

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'fact_orders'


---------------------------------------------------------------------------------
-- Dimensions Exploration: identifying unique values/categories in each dimension
---------------------------------------------------------------------------------

-- Explore the dim_customers table
SELECT DISTINCT state FROM dim_customers;
SELECT DISTINCT city FROM dim_customers;
SELECT DISTINCT state, city FROM dim_customers;

-- Explore the dim_products table
SELECT DISTINCT category FROM dim_products;
SELECT DISTINCT sub_category FROM dim_products;
SELECT DISTINCT category, sub_category FROM dim_products;

-- Explore the date column (identifying the earliest and latest dates (boundaries) 
-- and understanding the timespan)
SELECT 
    MIN(order_date),
    MAX(order_date),
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date))
FROM fact_orders;


----------------------------------------------------------------------------------
-- Measures Exploration: calculating key metrics, the highest level of aggregation
----------------------------------------------------------------------------------

-- What is the total sales?
SELECT 
SUM(amount) AS total_sales
FROM fact_orders;

-- How many items are sold?
SELECT 
SUM(quantity) AS total_quantity
FROM fact_orders;

-- What is the total number of orders?
SELECT 
COUNT(DISTINCT order_id) AS total_orders
FROM fact_orders;

-- What is the total number of products?
SELECT 
COUNT(DISTINCT product_key) AS total_products
FROM dim_products;

-- What is the total number of customers?
SELECT 
COUNT(DISTINCT customer_key) AS total_customers
FROM dim_customers;

-- What is the total customers who has placed an order?
SELECT 
COUNT(DISTINCT customer_key) AS total_customers
FROM fact_orders;

-- Build a report for the above calculations
SELECT 'Total Sales' AS measure_name, SUM(amount) AS measure_value FROM fact_orders
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM fact_orders
UNION ALL
SELECT 'Total Orders' AS measure_name, COUNT(DISTINCT order_id) AS measure_value FROM fact_orders
UNION ALL
SELECT 'Total Products' AS measure_name, COUNT(DISTINCT product_key) AS measure_value FROM dim_products
UNION ALL
SELECT 'Total Customers' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM dim_customers
UNION ALL
SELECT 'Total Customers Made Orders' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM fact_orders;


---------------------------------------------------------------------------------
-- Magnitude Exploration: comparing the measure values by different categories
---------------------------------------------------------------------------------

-- What is the total number of customers by state
SELECT 
    state, 
    COUNT(DISTINCT customer_key) AS total_customers
FROM dim_customers
GROUP BY state
ORDER BY total_customers DESC;

-- What is the total number of items sold by category?
SELECT 
    p.category,
    SUM(o.quantity) AS total_items_sold
FROM fact_orders AS o
LEFT JOIN dim_products p 
    ON o.product_key = p.product_key
GROUP BY p.category
ORDER BY total_items_sold DESC;

-- What is the total revenue generated by category?
SELECT 
    p.category,
    SUM(o.amount) AS total_revenue
FROM fact_orders AS o
LEFT JOIN dim_products p 
    ON o.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by customer?
SELECT 
    c.customer_key,
    c.customer_name,
    SUM(o.amount) AS total_revenue
FROM fact_orders AS o
LEFT JOIN dim_customers c
    ON o.customer_key = c.customer_key
GROUP BY 
    c.customer_key,
    c.customer_name
ORDER BY total_revenue DESC;

-- What is the distribution of items sold across cities?
SELECT 
    c.city, 
    SUM(o.quantity) AS total_quantity_sold
FROM fact_orders AS o
LEFT JOIN dim_customers AS c
ON o.customer_key = c.customer_key
GROUP BY c.city
ORDER BY total_quantity_sold DESC;

-- What is the total profit generted by state?
SELECT
    c.state,
    SUM(o.profit) AS total_profit
FROM fact_orders AS o
LEFT JOIN dim_customers AS c
ON o.customer_key = c.customer_key
GROUP BY c.state
ORDER BY total_profit DESC;


----------------------------------------------------------------------------------
-- Ranking Exploration: identifying the Top N performers and Bottom N performers
----------------------------------------------------------------------------------

-- Which 5 category and products generate the highest revenue?
SELECT TOP 5
    p.category,
    p.product_key, 
    SUM(o.amount) AS total_revenue
FROM fact_orders AS o
LEFT JOIN dim_products AS p
ON o.product_key = p.product_key
GROUP BY 
    p.category,
    p.product_key
ORDER BY total_revenue DESC;

-- What are the 8 worst-performing cities in terms of profit?
SELECT * 
FROM (
    SELECT
        c.state,
        c.city,
        SUM(o.profit) AS total_profit,
        ROW_NUMBER() OVER (ORDER BY SUM(o.profit)) AS rank_cities
    FROM fact_orders AS o
    LEFT JOIN dim_customers AS c
    ON o.customer_key = c.customer_key
    GROUP BY c.state, c.city
    ) AS t
WHERE t.rank_cities <= 8

-- Which 3 customers generate the most profit?
SELECT * 
FROM 
    (SELECT
        c.customer_name,
        c.customer_key,
        SUM(o.profit) AS total_profit,
        ROW_NUMBER() OVER (ORDER BY SUM(o.profit) DESC) AS rank_customers
    FROM fact_orders AS o
    LEFT JOIN dim_customers AS c
    ON o.customer_key = c.customer_key
    GROUP BY 
        c.customer_name,
        c.customer_key) AS t
WHERE t.rank_customers <= 3;
